/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "kat.h"

float *average_1_svc(Y_arr *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Average function has been called...\n");
	
	float sum=0;
	int i;

	for(i=0;i<argp->Y_size;i++)
		sum+=argp->Y.Y_val[i];
	
	result=sum/argp->Y_size;
	
	return &result;
}

max_min *maxmin_1_svc(Y_arr *argp, struct svc_req *rqstp)
{
	static max_min  result;

	printf("Max Min function has been called...\n");

	int i;

	result.max=-999999;
	result.min=999999;
	
	for(i=0;i<argp->Y_size;i++)
		if(argp->Y.Y_val[i]>result.max)
			result.max=argp->Y.Y_val[i];
			
	for(i=0;i<argp->Y_size;i++)
		if(argp->Y.Y_val[i]<result.min)
			result.min=argp->Y.Y_val[i];

	return &result;
}

aY *product_1_svc(a_mul_Y *argp, struct svc_req *rqstp)
{
	static aY  result;

	printf("a*Y[] function has been called...\n");

	result.prod.prod_len=argp->Y_size;
	result.prod.prod_val=(float *)malloc(argp->Y_size*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->Y_size;i++)
		result.prod.prod_val[i]=argp->a*argp->Y.Y_val[i];

	return &result;
}
