/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kat.h"

bool_t
xdr_Y_arr (XDR *xdrs, Y_arr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, 25,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Y_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_a_mul_Y (XDR *xdrs, a_mul_Y *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, 25,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Y_size))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aY (XDR *xdrs, aY *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prod.prod_val, (u_int *) &objp->prod.prod_len, 25,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
